### ISSUE TITLE
Docs have 404 due to issue in upstream .proto

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-service-management#123]
see: 👇 
```
 docs/v1.ServiceManagerClient.html
   [404] docs/service-management/overview
   [404] docs/google.api.servicemanagement.v1.RolloutStatus
```

**Comment by chingor13** [comment]
> docs/service-management/overview

This one can be fixed by correctly using the full URL with host.

> docs/google.api.servicemanagement.v1.RolloutStatus

This one comes from a link to an enum nested within a message. [link](https://github.com/googleapis/googleapis/blob/eb0e80a068bbe97be9e0000238d6ee173c2c5635/google/api/servicemanagement/v1/servicemanager.proto#L418), [enum](https://github.com/googleapis/googleapis/blob/eb0e80a068bbe97be9e0000238d6ee173c2c5635/google/api/servicemanagement/v1/resources.proto#L234)

**Comment by sofisl** [comment]
I don't think this is an issue anymore, tests seem to be passing.
